import { Site } from './types';

// 100 additional independent fashion sites, curated for model-led, non-white-background visual references.
export const EXTRA_SITES: Site[] = [
  { n: "Soft Surroundings", u: "https://www.softsurroundings.com", t: ["美国", "中老年", "有人模", "场景图"], c: "elegant" },
  { n: "J.Jill", u: "https://www.jjill.com", t: ["美国", "中年", "有人模", "常规"], c: "elegant" },
  { n: "Chico's", u: "https://www.chicos.com", t: ["美国", "中老年", "有人模", "通勤"], c: "elegant" },
  { n: "Sundance Catalog", u: "https://www.sundancecatalog.com", t: ["美国", "中年", "有人模", "自然场景"], c: "linen" },
  { n: "Johnny Was", u: "https://www.johnnywas.com", t: ["美国", "中年", "有人模", "印花"], c: "linen" },
  { n: "April Cornell", u: "https://www.aprilcornell.com", t: ["美国", "中老年", "有人模", "复古"], c: "linen" },
  { n: "Peruvian Connection", u: "https://www.peruvianconnection.com", t: ["美国", "中年", "有人模", "针织"], c: "elegant" },
  { n: "Cabi", u: "https://www.cabionline.com", t: ["美国", "中年", "有人模", "通勤"], c: "elegant" },
  { n: "Frances Valentine", u: "https://francesvalentine.com", t: ["美国", "中年", "有人模", "复古"], c: "elegant" },
  { n: "Draper James", u: "https://draperjames.com", t: ["美国", "常规", "有人模", "南方风"], c: "elegant" },
  { n: "Christy Dawn", u: "https://christydawn.com", t: ["美国", "常规", "有人模", "自然场景"], c: "linen" },
  { n: "DÔEN", u: "https://shopdoen.com", t: ["美国", "常规", "有人模", "法式复古"], c: "french" },
  { n: "Emerson Fry", u: "https://emersonfry.com", t: ["美国", "常规", "有人模", "极简"], c: "linen" },
  { n: "Zuri", u: "https://www.shopzuri.com", t: ["美国", "中年", "有人模", "印花"], c: "elegant" },
  { n: "Nooworks", u: "https://nooworks.com", t: ["美国", "常规", "有人模", "艺术印花"], c: "young" },
  { n: "Magnolia Pearl", u: "https://magnoliapearl.com", t: ["美国", "中年", "有人模", "复古场景"], c: "linen" },
  { n: "Bryn Walker", u: "https://www.brynwalker.com", t: ["美国", "中老年", "有人模", "宽松"], c: "linen" },
  { n: "XCVI", u: "https://www.xcvi.com", t: ["美国", "中年", "有人模", "休闲"], c: "elegant" },
  { n: "Cut Loose", u: "https://cutloose.com", t: ["美国", "中老年", "有人模", "宽松"], c: "linen" },
  { n: "Habitat Clothes", u: "https://habitatclothes.com", t: ["美国", "中老年", "有人模", "日常"], c: "linen" },
  { n: "FLAX", u: "https://flaxdesigns.com", t: ["美国", "中老年", "有人模", "亚麻"], c: "linen" },
  { n: "Inherit Co.", u: "https://www.inheritco.com", t: ["美国", "常规", "有人模", "得体"], c: "elegant" },
  { n: "Avara", u: "https://shopavara.com", t: ["美国", "常规", "有人模", "精品店"], c: "elegant" },
  { n: "Ivy City Co", u: "https://ivycityco.com", t: ["美国", "常规", "有人模", "连衣裙"], c: "gown" },
  { n: "Hill House Home", u: "https://www.hillhousehome.com", t: ["美国", "常规", "有人模", "生活方式"], c: "french" },
  { n: "Kiyonna", u: "https://www.kiyonna.com", t: ["美国", "大码", "有人模", "成熟"], c: "curve" },
  { n: "Karina Dresses", u: "https://www.karinadresses.com", t: ["美国", "中年", "有人模", "连衣裙"], c: "curve" },
  { n: "Z Supply", u: "https://zsupplyclothing.com", t: ["美国", "常规", "有人模", "休闲"], c: "young" },
  { n: "Faherty", u: "https://fahertybrand.com", t: ["美国", "常规", "有人模", "户外场景"], c: "linen" },
  { n: "Toad&Co", u: "https://www.toadandco.com", t: ["美国", "常规", "有人模", "户外"], c: "sport" },
  { n: "Seasalt Cornwall", u: "https://www.seasaltcornwall.com", t: ["英国", "中年", "有人模", "自然场景"], c: "linen" },
  { n: "White Stuff", u: "https://www.whitestuff.com", t: ["英国", "中年", "有人模", "日常"], c: "elegant" },
  { n: "FatFace", u: "https://www.fatface.com", t: ["英国", "常规", "有人模", "户外场景"], c: "elegant" },
  { n: "Boden", u: "https://www.boden.com", t: ["英国", "中年", "有人模", "印花"], c: "elegant" },
  { n: "TOAST", u: "https://www.toa.st", t: ["英国", "中年", "有人模", "极简场景"], c: "linen" },
  { n: "Celtic & Co", u: "https://www.celticandco.com", t: ["英国", "中年", "有人模", "针织"], c: "linen" },
  { n: "Sahara London", u: "https://saharalondon.com", t: ["英国", "中老年", "有人模", "宽松"], c: "elegant" },
  { n: "Adini", u: "https://www.adini.co.uk", t: ["英国", "中老年", "有人模", "印花"], c: "elegant" },
  { n: "Nomads Clothing", u: "https://nomadsclothing.com", t: ["英国", "中年", "有人模", "自然风"], c: "linen" },
  { n: "David Nieper", u: "https://www.davidnieper.co.uk", t: ["英国", "中老年", "有人模", "成熟"], c: "elegant" },
  { n: "Kettlewell Colours", u: "https://kettlewellcolours.com", t: ["英国", "中年", "有人模", "色彩"], c: "elegant" },
  { n: "Wyse London", u: "https://wyselondon.com", t: ["英国", "中年", "有人模", "彩色针织"], c: "elegant" },
  { n: "Baukjen", u: "https://www.baukjen.com", t: ["英国", "中年", "有人模", "通勤"], c: "elegant" },
  { n: "NRBY", u: "https://nrbyclothing.com", t: ["英国", "中年", "有人模", "休闲"], c: "elegant" },
  { n: "Brora", u: "https://www.broraonline.com", t: ["英国", "中年", "有人模", "针织"], c: "elegant" },
  { n: "Lily & Me", u: "https://www.lilyandmeclothing.com", t: ["英国", "中年", "有人模", "印花"], c: "linen" },
  { n: "Joe Browns", u: "https://www.joebrowns.co.uk", t: ["英国", "中老年", "有人模", "复古"], c: "elegant" },
  { n: "Kit and Kaboodal", u: "https://kitandkaboodal.com", t: ["英国", "中老年", "有人模", "宽松"], c: "linen" },
  { n: "Aspiga", u: "https://www.aspiga.com", t: ["英国", "中年", "有人模", "度假场景"], c: "linen" },
  { n: "RIXO", u: "https://rixolondon.com", t: ["英国", "常规", "有人模", "复古连衣裙"], c: "gown" },
  { n: "Saint + Sofia", u: "https://saintandsofia.com", t: ["英国", "中年", "有人模", "都市"], c: "elegant" },
  { n: "ME+EM", u: "https://www.meandem.com", t: ["英国", "中年", "有人模", "通勤"], c: "elegant" },
  { n: "Hope & Ivy", u: "https://hopeandivy.co.uk", t: ["英国", "常规", "有人模", "印花礼服"], c: "gown" },
  { n: "Nobody's Child", u: "https://www.nobodyschild.com", t: ["英国", "常规", "有人模", "连衣裙"], c: "young" },
  { n: "Mistral", u: "https://www.mistral-online.com", t: ["英国", "中年", "有人模", "自然印花"], c: "linen" },
  { n: "Deerberg", u: "https://www.deerberg.de", t: ["德国", "中老年", "有人模", "自然风"], c: "linen" },
  { n: "Hessnatur", u: "https://www.hessnatur.com/de", t: ["德国", "中年", "有人模", "天然面料"], c: "linen" },
  { n: "Waschbär", u: "https://www.waschbaer.de", t: ["德国", "中老年", "有人模", "环保"], c: "linen" },
  { n: "Gudrun Sjöden DE", u: "https://www.gudrunsjoden.com/de-de", t: ["德国", "中老年", "有人模", "彩色印花"], c: "linen" },
  { n: "Blutsgeschwister", u: "https://www.blutsgeschwister.de", t: ["德国", "常规", "有人模", "复古印花"], c: "young" },
  { n: "LANIUS", u: "https://www.lanius.com", t: ["德国", "中年", "有人模", "通勤"], c: "elegant" },
  { n: "ARMEDANGELS", u: "https://www.armedangels.com", t: ["德国", "常规", "有人模", "休闲"], c: "young" },
  { n: "Maas Natur", u: "https://www.maas-natur.de", t: ["德国", "中老年", "有人模", "天然面料"], c: "linen" },
  { n: "Grüne Erde", u: "https://www.grueneerde.com/de-at/", t: ["德国", "中年", "有人模", "自然生活"], c: "linen" },
  { n: "Tranquillo", u: "https://tranquillo-shop.de", t: ["德国", "中年", "有人模", "彩色"], c: "linen" },
  { n: "Chapati Design", u: "https://chapati.de", t: ["德国", "中年", "有人模", "波西"], c: "linen" },
  { n: "Ulla Popken DE", u: "https://www.ullapopken.de/de/", t: ["德国", "大码", "有人模", "成熟"], c: "curve" },
  { n: "KjBRAND", u: "https://www.kjbrand.de", t: ["德国", "大码", "有人模", "中年"], c: "curve" },
  { n: "Doris Streich", u: "https://www.doris-streich.de", t: ["德国", "大码", "有人模", "成熟"], c: "curve" },
  { n: "Via Appia Due", u: "https://www.via-appia-due.de", t: ["德国", "大码", "有人模", "通勤"], c: "curve" },
  { n: "Zizzi DE", u: "https://www.zizzi.de", t: ["德国", "大码", "有人模", "日常"], c: "curve" },
  { n: "Studio Untold", u: "https://www.studio-untold.com", t: ["德国", "大码", "有人模", "年轻休闲"], c: "curve" },
  { n: "Sheego", u: "https://www.sheego.de", t: ["德国", "大码", "有人模", "常规"], c: "curve" },
  { n: "Moshiki", u: "https://www.moshiki.com", t: ["德国", "中年", "有人模", "彩色宽松"], c: "linen" },
  { n: "Alife & Kickin", u: "https://alifeandkickin.com", t: ["德国", "常规", "有人模", "休闲户外"], c: "sport" },
  { n: "Medicine", u: "https://wearmedicine.com", t: ["波兰", "东欧", "有人模", "艺术印花"], c: "euro" },
  { n: "Mohito", u: "https://www.mohito.com", t: ["波兰", "东欧", "有人模", "通勤"], c: "euro" },
  { n: "Tatuum", u: "https://www.tatuum.com", t: ["波兰", "东欧", "有人模", "中年"], c: "euro" },
  { n: "Solar", u: "https://solar.com.pl", t: ["波兰", "东欧", "有人模", "成熟"], c: "euro" },
  { n: "Taranko", u: "https://taranko.com", t: ["波兰", "东欧", "有人模", "优雅"], c: "euro" },
  { n: "RISK made in Warsaw", u: "https://www.riskmadeinwarsaw.com", t: ["波兰", "东欧", "有人模", "设计感"], c: "euro" },
  { n: "NAGO", u: "https://nago.com", t: ["波兰", "东欧", "有人模", "极简"], c: "euro" },
  { n: "By Insomnia", u: "https://byinsomnia.com/en/", t: ["波兰", "东欧", "有人模", "休闲"], c: "euro" },
  { n: "KARKO", u: "https://karko.pl", t: ["波兰", "东欧", "大码", "有人模"], c: "curve" },
  { n: "L'AF", u: "https://laf-laf.pl", t: ["波兰", "东欧", "有人模", "礼服"], c: "gown" },
  { n: "Potis & Verso", u: "https://potisandverso.com", t: ["波兰", "东欧", "有人模", "成熟通勤"], c: "euro" },
  { n: "VISSAVI", u: "https://vissavi.pl", t: ["波兰", "东欧", "有人模", "连衣裙"], c: "euro" },
  { n: "NISSA", u: "https://nissa.com", t: ["罗马尼亚", "东欧", "有人模", "优雅"], c: "gown" },
  { n: "StarShinerS", u: "https://starshiners.ro", t: ["罗马尼亚", "东欧", "有人模", "连衣裙"], c: "gown" },
  { n: "DY Fashion", u: "https://www.dyfashion.ro", t: ["罗马尼亚", "东欧", "有人模", "成熟"], c: "euro" },
  { n: "YOKKO", u: "https://www.yokko.com", t: ["罗马尼亚", "东欧", "有人模", "通勤"], c: "euro" },
  { n: "MIZAR", u: "https://www.mizar.ro", t: ["罗马尼亚", "东欧", "有人模", "常规"], c: "euro" },
  { n: "VOVK", u: "https://vovk.com", t: ["乌克兰", "东欧", "有人模", "通勤"], c: "euro" },
  { n: "MustHave", u: "https://musthave.ua/ua", t: ["乌克兰", "东欧", "有人模", "常规"], c: "euro" },
  { n: "GEPUR", u: "https://gepur.com", t: ["乌克兰", "东欧", "有人模", "AI感"], c: "young" },
  { n: "One by One", u: "https://onebyone.ua", t: ["乌克兰", "东欧", "有人模", "常规"], c: "euro" },
  { n: "Son de Flor", u: "https://sondeflor.com", t: ["立陶宛", "东欧", "有人模", "亚麻场景"], c: "linen" },
  { n: "Linenfox", u: "https://linenfoxclothes.com", t: ["立陶宛", "东欧", "有人模", "亚麻"], c: "linen" },
  { n: "Sugarbird", u: "https://sugarbird.com", t: ["匈牙利", "东欧", "有人模", "印花"], c: "euro" },
  { n: "PS Fashion", u: "https://www.psfashion.com", t: ["塞尔维亚", "东欧", "有人模", "成熟"], c: "euro" },
];
