import { Site } from './types';

// Strictly re-screened batch:
// - not merely "not pure white"
// - rejects empty white / grey / beige studio backdrops
// - prioritises outdoor, street, home, manor, coastal and other lived-in scenes
export const EXTRA_SITES: Site[] = [
  // US — lifestyle / outdoor / lived-in interiors
  { n: "Brochu Walker", u: "https://brochuwalker.com", t: ["美国", "实景优先", "有人模", "室内/街景"], c: "elegant" },
  { n: "Christy Dawn", u: "https://christydawn.com", t: ["美国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "DÔEN", u: "https://www.shopdoen.com", t: ["美国", "实景优先", "有人模", "度假/庄园场景"], c: "french" },
  { n: "Magnolia Pearl", u: "https://magnoliapearl.com", t: ["美国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Frank & Eileen", u: "https://www.frankandeileen.com", t: ["美国", "实景优先", "有人模", "室内/街景"], c: "elegant" },
  { n: "Toad&Co", u: "https://www.toadandco.com", t: ["美国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "Faherty", u: "https://fahertybrand.com", t: ["美国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Carve Designs", u: "https://www.carvedesigns.com", t: ["美国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "Title Nine", u: "https://www.titlenine.com", t: ["美国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "prAna Women", u: "https://www.prana.com/women.html", t: ["美国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "Outerknown Women", u: "https://www.outerknown.com/collections/womens", t: ["美国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Marine Layer Women", u: "https://www.marinelayer.com/collections/gals", t: ["美国", "实景优先", "有人模", "街景/彩色场景"], c: "young" },
  { n: "Cleobella", u: "https://cleobella.com", t: ["美国", "实景优先", "有人模", "度假/庄园场景"], c: "french" },
  { n: "Natalie Martin", u: "https://nataliemartin.com", t: ["美国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Banjanan", u: "https://www.banjanan.com", t: ["美国", "实景优先", "有人模", "度假/庄园场景"], c: "french" },
  { n: "MIRTH", u: "https://mirthcaftans.com", t: ["美国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "THE GREAT.", u: "https://thisisthegreat.com", t: ["美国", "实景优先", "有人模", "室内/街景"], c: "elegant" },
  { n: "Nooworks", u: "https://nooworks.com", t: ["美国", "实景优先", "有人模", "街景/彩色场景"], c: "young" },
  { n: "April Cornell", u: "https://www.aprilcornell.com", t: ["美国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Peruvian Connection", u: "https://www.peruvianconnection.com", t: ["美国", "实景优先", "有人模", "室内/街景"], c: "elegant" },
  { n: "Soft Surroundings", u: "https://www.softsurroundings.com", t: ["美国", "实景优先", "有人模", "室内/街景"], c: "elegant" },
  { n: "Johnny Was", u: "https://www.johnnywas.com", t: ["美国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Draper James", u: "https://draperjames.com", t: ["美国", "实景优先", "有人模", "室内/街景"], c: "elegant" },
  { n: "Hill House Home", u: "https://www.hillhousehome.com", t: ["美国", "实景优先", "有人模", "度假/庄园场景"], c: "french" },
  { n: "Jenni Kayne", u: "https://www.jennikayne.com", t: ["美国", "实景优先", "有人模", "室内/街景"], c: "elegant" },
  { n: "Ulla Johnson", u: "https://ullajohnson.com", t: ["美国", "实景优先", "有人模", "氛围场景"], c: "gown" },
  { n: "Sea New York", u: "https://sea-newyork.com", t: ["美国", "实景优先", "有人模", "度假/庄园场景"], c: "french" },
  { n: "Emerson Fry", u: "https://emersonfry.com", t: ["美国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "KÜHL Women", u: "https://www.kuhl.com/kuhl/womens/", t: ["美国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "Krimson Klover", u: "https://krimsonklover.com", t: ["美国", "实景优先", "有人模", "户外场景"], c: "sport" },

  // UK — countryside / coastal / urban lifestyle
  { n: "Seasalt Cornwall", u: "https://www.seasaltcornwall.com", t: ["英国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "FatFace Women", u: "https://www.fatface.com/women", t: ["英国", "实景优先", "有人模", "室内/街景"], c: "elegant" },
  { n: "TOAST", u: "https://www.toa.st", t: ["英国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Celtic & Co", u: "https://www.celticandco.com", t: ["英国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Nomads Clothing", u: "https://nomadsclothing.com", t: ["英国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Aspiga", u: "https://www.aspiga.com", t: ["英国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "RIXO", u: "https://rixolondon.com", t: ["英国", "实景优先", "有人模", "氛围场景"], c: "gown" },
  { n: "Mistral", u: "https://www.mistral-online.com", t: ["英国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Brakeburn", u: "https://www.brakeburn.com", t: ["英国", "实景优先", "有人模", "室内/街景"], c: "elegant" },
  { n: "Weird Fish Women", u: "https://www.weirdfish.co.uk/c/women", t: ["英国", "实景优先", "有人模", "室内/街景"], c: "elegant" },
  { n: "Passenger Women", u: "https://www.passenger-clothing.com/collections/womens", t: ["英国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "Finisterre Women", u: "https://finisterre.com/collections/womens", t: ["英国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "Crew Clothing Women", u: "https://www.crewclothing.co.uk/womens", t: ["英国", "实景优先", "有人模", "室内/街景"], c: "elegant" },
  { n: "White Stuff", u: "https://www.whitestuff.com", t: ["英国", "实景优先", "有人模", "室内/街景"], c: "elegant" },
  { n: "Plümo", u: "https://www.plumo.com", t: ["英国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "O Pioneers", u: "https://opioneers.com", t: ["英国", "实景优先", "有人模", "度假/庄园场景"], c: "french" },
  { n: "Pink City Prints", u: "https://pinkcityprints.com", t: ["英国", "实景优先", "有人模", "度假/庄园场景"], c: "french" },
  { n: "Justine Tabak", u: "https://justinetabak.co.uk", t: ["英国", "实景优先", "有人模", "度假/庄园场景"], c: "french" },
  { n: "Meadows", u: "https://meadows-store.com", t: ["英国", "实景优先", "有人模", "度假/庄园场景"], c: "french" },
  { n: "Lucy & Yak", u: "https://lucyandyak.com", t: ["英国", "实景优先", "有人模", "街景/彩色场景"], c: "young" },
  { n: "Run & Fly", u: "https://www.runandfly.co.uk", t: ["英国", "实景优先", "有人模", "街景/彩色场景"], c: "young" },
  { n: "Palava", u: "https://palava.co", t: ["英国", "实景优先", "有人模", "度假/庄园场景"], c: "french" },
  { n: "Joe Browns", u: "https://www.joebrowns.co.uk", t: ["英国", "实景优先", "有人模", "室内/街景"], c: "elegant" },
  { n: "Poetry Fashion", u: "https://www.poetryfashion.com", t: ["英国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Gudrun Sjöden UK", u: "https://www.gudrunsjoden.com/en-gb", t: ["英国", "实景优先", "有人模", "自然场景"], c: "linen" },

  // Germany — nature / outdoor / colourful lifestyle
  { n: "Deerberg", u: "https://www.deerberg.de", t: ["德国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Hessnatur", u: "https://www.hessnatur.com/de", t: ["德国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Waschbär", u: "https://www.waschbaer.de", t: ["德国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Gudrun Sjöden DE", u: "https://www.gudrunsjoden.com/de-de", t: ["德国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Blutsgeschwister", u: "https://www.blutsgeschwister.de", t: ["德国", "实景优先", "有人模", "街景/彩色场景"], c: "young" },
  { n: "ARMEDANGELS", u: "https://www.armedangels.com", t: ["德国", "实景优先", "有人模", "街景/彩色场景"], c: "young" },
  { n: "Grüne Erde Mode", u: "https://www.grueneerde.com/de-at/produkte/mode", t: ["德国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Tranquillo", u: "https://tranquillo-shop.de", t: ["德国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Chapati Design", u: "https://chapati.de", t: ["德国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Moshiki", u: "https://www.moshiki.com", t: ["德国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Alife & Kickin", u: "https://alifeandkickin.com", t: ["德国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "Ragwear", u: "https://www.ragwear.com", t: ["德国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "Elkline", u: "https://www.elkline.de", t: ["德国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "Maloja Women", u: "https://www.maloja.com/de-de/women", t: ["德国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "VAUDE Women", u: "https://www.vaude.com/de/de/damen.html", t: ["德国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "Schöffel Women", u: "https://www.schoeffel.com/de/de/damen/", t: ["德国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "bleed clothing", u: "https://www.bleed-clothing.com", t: ["德国", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "recolution", u: "https://www.recolution.de", t: ["德国", "实景优先", "有人模", "街景/彩色场景"], c: "young" },
  { n: "HempAge", u: "https://www.hempage.de", t: ["德国", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Derbe Hamburg", u: "https://www.derbe-hamburg.de", t: ["德国", "实景优先", "有人模", "户外场景"], c: "sport" },

  // Eastern Europe — campaign / city / nature / heritage
  { n: "Medicine", u: "https://wearmedicine.com", t: ["东欧", "实景优先", "有人模", "城市/氛围场景"], c: "euro" },
  { n: "RISK made in Warsaw", u: "https://www.riskmadeinwarsaw.com", t: ["东欧", "实景优先", "有人模", "城市/氛围场景"], c: "euro" },
  { n: "The Odder Side", u: "https://theodderside.com", t: ["东欧", "实景优先", "有人模", "城市/氛围场景"], c: "euro" },
  { n: "NAOKO", u: "https://naoko-store.com", t: ["东欧", "实景优先", "有人模", "城市/氛围场景"], c: "euro" },
  { n: "Femi Stories", u: "https://femistories.com", t: ["东欧", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "Pan tu nie stał", u: "https://pantuniestal.com", t: ["东欧", "实景优先", "有人模", "街景/彩色场景"], c: "young" },
  { n: "Quiosque", u: "https://quiosque.pl", t: ["东欧", "实景优先", "有人模", "城市/氛围场景"], c: "euro" },
  { n: "Tatuum", u: "https://www.tatuum.com", t: ["东欧", "实景优先", "有人模", "城市/氛围场景"], c: "euro" },
  { n: "bynamesakke", u: "https://bynamesakke.com", t: ["东欧", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "VOVK", u: "https://vovk.com", t: ["东欧", "实景优先", "有人模", "城市/氛围场景"], c: "euro" },
  { n: "One by One", u: "https://onebyone.ua", t: ["东欧", "实景优先", "有人模", "城市/氛围场景"], c: "euro" },
  { n: "ETNODIM", u: "https://etnodim.com", t: ["东欧", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "GUNIA Project", u: "https://guniaproject.com", t: ["东欧", "实景优先", "有人模", "度假/庄园场景"], c: "french" },
  { n: "Sleeper", u: "https://the-sleeper.com", t: ["东欧", "实景优先", "有人模", "氛围场景"], c: "gown" },
  { n: "CHERESHNIVSKA", u: "https://chereshnivska.com", t: ["东欧", "实景优先", "有人模", "城市/氛围场景"], c: "euro" },
  { n: "Son de Flor", u: "https://sondeflor.com", t: ["东欧", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Linenfox", u: "https://linenfoxclothes.com", t: ["东欧", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "notPERFECTLINEN", u: "https://notperfectlinen.com", t: ["东欧", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "The Knotty Ones", u: "https://www.theknottyones.com", t: ["东欧", "实景优先", "有人模", "自然场景"], c: "linen" },
  { n: "Sugarbird", u: "https://sugarbird.com", t: ["东欧", "实景优先", "有人模", "城市/氛围场景"], c: "euro" },
  { n: "Nanushka", u: "https://www.nanushka.com", t: ["东欧", "实景优先", "有人模", "氛围场景"], c: "gown" },
  { n: "IVKO Woman", u: "https://ivko.com", t: ["东欧", "实景优先", "有人模", "城市/氛围场景"], c: "euro" },
  { n: "WOOX", u: "https://www.woox.cz", t: ["东欧", "实景优先", "有人模", "户外场景"], c: "sport" },
  { n: "Mona Fashion", u: "https://www.monaonline.com", t: ["东欧", "实景优先", "有人模", "城市/氛围场景"], c: "euro" },
  { n: "Bohempia", u: "https://www.bohempia.eu", t: ["东欧", "实景优先", "有人模", "户外场景"], c: "sport" },
];
